# Generated by Django 3.2 on 2021-04-10 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique_for_date='publish')),
                ('courses_details', models.TextField()),
                ('video', models.FileField(upload_to='course/videos/')),
                ('imag_front', models.ImageField(upload_to='course_img/')),
                ('imag_back', models.ImageField(upload_to='course_img/')),
                ('imag_top', models.ImageField(blank=True, null=True, upload_to='course_img/')),
                ('courses_type', models.CharField(choices=[('Month', 'Month'), ('Year', 'Year')], default='Month', max_length=22)),
                ('courses_duration', models.CharField(max_length=20)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_course', models.DateField(auto_now_add=True)),
                ('updated_course', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('New', 'New'), ('Cancelled', 'Cancelled'), ('Approved', 'Approved')], default='New', max_length=50)),
                ('name', models.CharField(max_length=300)),
                ('father_name', models.CharField(max_length=300)),
                ('mother_name', models.CharField(max_length=300)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=25)),
                ('maritial_status', models.CharField(choices=[('Marred', 'Marred'), ('Unmarred', 'Unmarred')], default='Unmarred', max_length=50)),
                ('Districk', models.CharField(max_length=100)),
                ('Post_office', models.CharField(max_length=100)),
                ('Village', models.CharField(max_length=100)),
                ('Birthday', models.CharField(max_length=100)),
                ('Education_qualification', models.CharField(choices=[('SSC', 'SSC'), ('HSC', 'HSC')], default='SSC', max_length=100)),
                ('student_img', models.ImageField(upload_to='student/student_img')),
                ('mobileNumber', models.CharField(default='+880 ', max_length=15)),
                ('email', models.EmailField(default='some@gmail.com', max_length=55)),
                ('Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.courses')),
            ],
        ),
    ]
